name: Test coverage

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Collect coverage for client
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: client
          annotations: all

      - name: Collect coverage for server
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: server
          annotations: all